name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-template: '$MAJOR.$MINOR.$PATCH'
exclude-labels:
  - 'skip-changelog'
template: |
  ## What's Changed
  $CHANGES

  ## New Contributors
  $CONTRIBUTORS

  ## Full Changelog
  $FULL_CHANGES

